name: Tests
on: [push, pull_request]

jobs:
  code-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage llvmlite


      - name: Clone BasicTestSuite
        run: git clone https://github.com/cocode/BasicTestSuite
      
      - name: Run tests with coverage
        run: |
          ./run_coverage_tests.py  
          coverage xml            # generates coverage.xml for codecov
          coverage report         # shows coverage in workflow logs
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
