name: Manual Code Quality Checks

on:
  workflow_dispatch:  # Allows manual trigger via GitHub web UI

jobs:
  quality-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff black mypy bandit safety pytest pytest-cov

#      - name: Run Ruff (lint)
#        run: ruff check
#
#      - name: Run Black (format check)
#        run: black --check .
#
#      - name: Run Mypy (type check)
#        run: mypy .
#
#      - name: Run Bandit (security check)
#        run: bandit -r .
#
#      - name: Run Safety (dependency vulnerability check)
#        run: safety check || true  # Reports vulnerabilities but doesn't fail build
#
      - name: Run Tests with Coverage
        run: pytest --cov=trekbasic test
